//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 软件工程机考系统 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal data() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("软件工程机考系统.data", typeof(data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 序号
        ///题干
        ///A
        ///B
        ///C
        ///D
        ///答案
        ///1软件生命周期一般包括：软件开发期和软件运行期，下述（   ）不是软件开发期所应包含
        ///需求分析
        ///结构设计
        ///程序编制
        ///软件维护
        ///D
        ///2软件是一种逻辑产品，它的开发主要是（   ）。
        ///研制
        ///拷贝
        ///再生产
        ///复制
        ///A
        ///3以文档作为驱动，适合于软件需求很明确的软件项目的生存周期模型是（   ）
        ///喷泉模型
        ///增量模型
        ///瀑布模型
        ///螺旋模型
        ///C
        ///4在软件生存周期中，（   ）阶段必须要回答的问题是“要解决的问题是做什么？”。
        ///详细设计
        ///可行性分析和项目开发计划
        ///概要设计
        ///软件测试
        ///B
        ///5软件产品与物质产品有很大区别，软件产品是一种（   ）产品
        ///有形
        ///消耗
        ///逻辑
        ///文档
        ///C
        ///6（   ）把瀑布模型和专家系统结合在一起，在开发的各个阶段上都利用相应的专家系统来帮助软件人员完成开发工作。
        ///原型模型
        ///螺旋模型
        ///基于知识的智能模型
        ///喷泉模型
        ///C
        ///7（   ）阶段是为每个模块完成的功能进行具体的描述，要把功能描述转变为精确的、结构化的过程描述。
        ///概要设计
        ///详细设计
        ///编码
        ///测试
        ///B
        ///8下列软件开发模型中，适合于 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
    }
}
